
package obuits;

import static obuits.MainFrmIts.lblFD;
import static obuits.MainFrmIts.lblID;
import static obuits.MainFrmIts.lblIDArt;
import static obuits.MainFrmIts.lblRD;
import static obuits.MainFrmIts.lblSD;
import static obuits.MainFrmIts.lblSDArt;
import static obuits.clsDefines.Strings.KEMITO_BAUDRATE;
import static obuits.clsDefines.Strings.KEMITO_DISBRD;
import static obuits.clsDefines.Strings.SUMITH_DISBRD;
import static obuits.clsSharedVariables.driverLoginEnabled;
import static obuits.clsSharedVariables.getDisBrdBaudRate;
import static obuits.clsSharedVariables.getDisBrdName;
import static obuits.clsSharedVariables.getDisBrdRetries;
import static obuits.clsSharedVariables.getDisbRdGap;
import static obuits.clsSharedVariables.getDisbRdRetryWaitTime;
import static obuits.clsSharedVariables.getFrontEnable;
import static obuits.clsSharedVariables.setDisBrdBaudRate;
import static obuits.clsSharedVariables.setDisBrdName;
import static obuits.clsSharedVariables.setDisBrdRetries;
import static obuits.clsSharedVariables.setDisbRdGap;
import static obuits.clsSharedVariables.setDisbRdRetryWaitTime;
import static obuits.clsSharedVariables.setFrontEnable;
import static obuits.clsSharedVariables.setIntEnable;
import static obuits.clsSharedVariables.setRearEnable;
import static obuits.clsSharedVariables.setSideEnable;

public class PanDisplayboard extends javax.swing.JPanel {

    String prev_control_name = "";

    public PanDisplayboard() {
        initComponents();
        int i = 0;
        int retry_time = 0;
        this.lblDisBrdMake.setVisible(false);
        this.cmbDisBrdMake.setVisible(false);
        lblNoRetries.setVisible(false);
        cmbNoRetries.setVisible(false);
        lblRetryWait.setVisible(true);
        cmbRetryWaitTime.setVisible(true);
        lblGap.setVisible(false);
        txtGap.setVisible(false);
        try {
            int g_dis_brd_retry_wait_time = getDisbRdRetryWaitTime();
            int g_dis_brd_no_retries = getDisBrdRetries();
            if (getDisBrdName() == SUMITH_DISBRD) {
                cmbDisBrdMake.setSelectedIndex(0);
                txtBaudRate.setText(String.valueOf(getDisBrdBaudRate()));
            } else {
                txtBaudRate.setText(String.valueOf(KEMITO_BAUDRATE));
                cmbDisBrdMake.setSelectedIndex(1);
            }

            cmbNoRetries.setSelectedItem(String.valueOf(g_dis_brd_no_retries));
            retry_time = g_dis_brd_retry_wait_time;
            cmbRetryWaitTime.setText(String.valueOf((retry_time)));

            txtGap.setText(String.valueOf((getDisbRdGap())));
            chkFrontDisplayBrd.setSelected(getFrontEnable());
            chkSideDisplayBrd.setSelected(clsSharedVariables.getSideEnable());
            chkRearDisplayBrd.setSelected(clsSharedVariables.getRearEnable());
            chkIntDisplayBrd.setSelected(clsSharedVariables.getIntEnable());
            this.radspecial.setSelected(clsSharedVariables.getArticulatedBus());
            chkSplSideDisplayBrd.setSelected(clsSharedVariables.getArtSideEnable());
            chkSplIntDisplayBrd.setSelected(clsSharedVariables.getArtIntEnable());
            if (radnormal.isSelected()) {
                splPane.setVisible(false);
            } else {
                splPane.setVisible(true);
                this.spinArtSideAddr.setValue(clsDefines.SD_ART_ADDR);
                this.spinArtIntAddr.setValue(clsDefines.ID_ART_ADDR);
            }

            if (cmbDisBrdMake.getSelectedItem().equals("Sumith")) {
                txtBaudRate.setText(String.valueOf(clsSharedVariables.getDisBrdBaudRate())); // String.valueOf(SUMITH_BAUDRATE));
            } else {
                txtBaudRate.setText(String.valueOf(KEMITO_BAUDRATE));
            }

            lblMsg.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (clsSharedVariables.getPidsDbEnable()) {
            chkPid.setSelected(true);
        } else {
            chkPid.setSelected(false);
        }
        if (clsSharedVariables.getDisplayDriverDb()) {
            this.chkDriverDb.setSelected(true);
        } else {
            chkDriverDb.setSelected(false);
        }

        if (driverLoginEnabled == true) {
            this.chkDriverDb.setVisible(true);
        } else {
            this.chkDriverDb.setVisible(false);
            clsSharedVariables.setDisplayDriverDb(false);
            chkDriverDb.setSelected(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblMsg = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        chkSideDisplayBrd = new javax.swing.JCheckBox();
        chkRearDisplayBrd = new javax.swing.JCheckBox();
        chkFrontDisplayBrd = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        chkIntDisplayBrd = new javax.swing.JCheckBox();
        lblNoRetries = new javax.swing.JLabel();
        cmbNoRetries = new javax.swing.JComboBox();
        lblRetryWait = new javax.swing.JLabel();
        lblDisBrdMake = new javax.swing.JLabel();
        cmbDisBrdMake = new javax.swing.JComboBox();
        lblBaudRate = new javax.swing.JLabel();
        txtBaudRate = new javax.swing.JTextField();
        lblConfigName = new javax.swing.JTextField();
        cmbRetryWaitTime = new javax.swing.JTextField();
        lblGap = new javax.swing.JLabel();
        txtGap = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radspecial = new javax.swing.JRadioButton();
        radnormal = new javax.swing.JRadioButton();
        splPane = new javax.swing.JPanel();
        chkSplSideDisplayBrd = new javax.swing.JCheckBox();
        chkSplIntDisplayBrd = new javax.swing.JCheckBox();
        spinArtSideAddr = new javax.swing.JSpinner();
        spinArtIntAddr = new javax.swing.JSpinner();
        chkPid = new javax.swing.JCheckBox();
        chkDriverDb = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(500, 430));

        lblMsg.setFont(lblMsg.getFont().deriveFont(lblMsg.getFont().getStyle() | java.awt.Font.BOLD, lblMsg.getFont().getSize()+5));
        lblMsg.setForeground(new java.awt.Color(0, 102, 0));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMsg.setText("Configuration Saved");

        btnSave.setBackground(new java.awt.Color(47, 49, 51));
        btnSave.setFont(btnSave.getFont().deriveFont(btnSave.getFont().getStyle() | java.awt.Font.BOLD, btnSave.getFont().getSize()+7));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setPreferredSize(new java.awt.Dimension(100, 42));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        chkSideDisplayBrd.setFont(chkSideDisplayBrd.getFont().deriveFont(chkSideDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkSideDisplayBrd.getFont().getSize()+7));
        chkSideDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkSideDisplayBrd.setSelected(true);
        chkSideDisplayBrd.setText("Side Display");
        chkSideDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkSideDisplayBrdFocusGained(evt);
            }
        });

        chkRearDisplayBrd.setFont(chkRearDisplayBrd.getFont().deriveFont(chkRearDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkRearDisplayBrd.getFont().getSize()+7));
        chkRearDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkRearDisplayBrd.setSelected(true);
        chkRearDisplayBrd.setText("Rear Display ");
        chkRearDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkRearDisplayBrdFocusGained(evt);
            }
        });
        chkRearDisplayBrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRearDisplayBrdActionPerformed(evt);
            }
        });

        chkFrontDisplayBrd.setFont(chkFrontDisplayBrd.getFont().deriveFont(chkFrontDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkFrontDisplayBrd.getFont().getSize()+7));
        chkFrontDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkFrontDisplayBrd.setSelected(true);
        chkFrontDisplayBrd.setText("Front Display");
        chkFrontDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkFrontDisplayBrdFocusGained(evt);
            }
        });
        chkFrontDisplayBrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrontDisplayBrdActionPerformed(evt);
            }
        });

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 102));
        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Front Display Enable");

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 102));
        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Front Display Enable");

        chkIntDisplayBrd.setFont(chkIntDisplayBrd.getFont().deriveFont(chkIntDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkIntDisplayBrd.getFont().getSize()+7));
        chkIntDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkIntDisplayBrd.setSelected(true);
        chkIntDisplayBrd.setText("Internal Display");
        chkIntDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkIntDisplayBrdFocusGained(evt);
            }
        });
        chkIntDisplayBrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntDisplayBrdActionPerformed(evt);
            }
        });

        lblNoRetries.setFont(lblNoRetries.getFont().deriveFont(lblNoRetries.getFont().getStyle() | java.awt.Font.BOLD, lblNoRetries.getFont().getSize()+5));
        lblNoRetries.setForeground(new java.awt.Color(0, 0, 102));
        lblNoRetries.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoRetries.setText("No Retries");

        cmbNoRetries.setFont(cmbNoRetries.getFont().deriveFont(cmbNoRetries.getFont().getStyle() | java.awt.Font.BOLD, cmbNoRetries.getFont().getSize()+5));
        cmbNoRetries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbNoRetries.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbNoRetriesFocusGained(evt);
            }
        });

        lblRetryWait.setFont(lblRetryWait.getFont().deriveFont(lblRetryWait.getFont().getStyle() | java.awt.Font.BOLD, lblRetryWait.getFont().getSize()+5));
        lblRetryWait.setForeground(new java.awt.Color(0, 0, 102));
        lblRetryWait.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRetryWait.setText("Retry Wait Time(ms)");

        lblDisBrdMake.setFont(lblDisBrdMake.getFont().deriveFont(lblDisBrdMake.getFont().getStyle() | java.awt.Font.BOLD, lblDisBrdMake.getFont().getSize()+5));
        lblDisBrdMake.setForeground(new java.awt.Color(0, 0, 102));
        lblDisBrdMake.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisBrdMake.setText("Displayboard Make");

        cmbDisBrdMake.setFont(cmbDisBrdMake.getFont().deriveFont(cmbDisBrdMake.getFont().getStyle() | java.awt.Font.BOLD, cmbDisBrdMake.getFont().getSize()+5));
        cmbDisBrdMake.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sumith", "Chemito" }));
        cmbDisBrdMake.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbDisBrdMakeFocusGained(evt);
            }
        });
        cmbDisBrdMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisBrdMakeActionPerformed(evt);
            }
        });

        lblBaudRate.setFont(lblBaudRate.getFont().deriveFont(lblBaudRate.getFont().getStyle() | java.awt.Font.BOLD, lblBaudRate.getFont().getSize()+5));
        lblBaudRate.setForeground(new java.awt.Color(0, 0, 102));
        lblBaudRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBaudRate.setText("Baudrate");

        txtBaudRate.setBackground(new java.awt.Color(240, 240, 240));
        txtBaudRate.setFont(txtBaudRate.getFont().deriveFont(txtBaudRate.getFont().getStyle() | java.awt.Font.BOLD, txtBaudRate.getFont().getSize()+5));
        txtBaudRate.setText("115200");
        txtBaudRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBaudRateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBaudRateFocusLost(evt);
            }
        });

        lblConfigName.setEditable(false);
        lblConfigName.setBackground(new java.awt.Color(23, 29, 32));
        lblConfigName.setFont(lblConfigName.getFont().deriveFont(lblConfigName.getFont().getStyle() | java.awt.Font.BOLD, lblConfigName.getFont().getSize()+10));
        lblConfigName.setForeground(new java.awt.Color(255, 255, 255));
        lblConfigName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblConfigName.setText("DISPLAY BOARD");
        lblConfigName.setPreferredSize(new java.awt.Dimension(500, 30));
        lblConfigName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblConfigNameActionPerformed(evt);
            }
        });

        cmbRetryWaitTime.setBackground(new java.awt.Color(240, 240, 240));
        cmbRetryWaitTime.setFont(cmbRetryWaitTime.getFont().deriveFont(cmbRetryWaitTime.getFont().getStyle() | java.awt.Font.BOLD, cmbRetryWaitTime.getFont().getSize()+5));
        cmbRetryWaitTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbRetryWaitTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbRetryWaitTimeFocusLost(evt);
            }
        });
        cmbRetryWaitTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRetryWaitTimeActionPerformed(evt);
            }
        });

        lblGap.setFont(lblGap.getFont().deriveFont(lblGap.getFont().getStyle() | java.awt.Font.BOLD, lblGap.getFont().getSize()+5));
        lblGap.setForeground(new java.awt.Color(0, 0, 102));
        lblGap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGap.setText("Gap betweenTransmission(ms)");

        txtGap.setBackground(new java.awt.Color(240, 240, 240));
        txtGap.setFont(txtGap.getFont().deriveFont(txtGap.getFont().getStyle() | java.awt.Font.BOLD, txtGap.getFont().getSize()+5));
        txtGap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGapFocusLost(evt);
            }
        });
        txtGap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGapActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 36));

        buttonGroup1.add(radspecial);
        radspecial.setFont(radspecial.getFont().deriveFont(radspecial.getFont().getStyle() | java.awt.Font.BOLD, radspecial.getFont().getSize()+7));
        radspecial.setForeground(new java.awt.Color(0, 0, 102));
        radspecial.setText("ARTICULATED");
        radspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radspecialActionPerformed(evt);
            }
        });

        buttonGroup1.add(radnormal);
        radnormal.setFont(radnormal.getFont().deriveFont(radnormal.getFont().getStyle() | java.awt.Font.BOLD, radnormal.getFont().getSize()+7));
        radnormal.setForeground(new java.awt.Color(0, 0, 102));
        radnormal.setSelected(true);
        radnormal.setText("NORMAL");
        radnormal.setContentAreaFilled(false);
        radnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radnormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radnormal)
                .addGap(42, 42, 42)
                .addComponent(radspecial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radnormal)
                    .addComponent(radspecial))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        chkSplSideDisplayBrd.setFont(chkSplSideDisplayBrd.getFont().deriveFont(chkSplSideDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkSplSideDisplayBrd.getFont().getSize()+7));
        chkSplSideDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkSplSideDisplayBrd.setSelected(true);
        chkSplSideDisplayBrd.setText("Articulated Side Display");
        chkSplSideDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkSplSideDisplayBrdFocusGained(evt);
            }
        });

        chkSplIntDisplayBrd.setFont(chkSplIntDisplayBrd.getFont().deriveFont(chkSplIntDisplayBrd.getFont().getStyle() | java.awt.Font.BOLD, chkSplIntDisplayBrd.getFont().getSize()+7));
        chkSplIntDisplayBrd.setForeground(new java.awt.Color(0, 0, 102));
        chkSplIntDisplayBrd.setSelected(true);
        chkSplIntDisplayBrd.setText("Articulated Internal Display ");
        chkSplIntDisplayBrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chkSplIntDisplayBrdFocusGained(evt);
            }
        });

        spinArtSideAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinArtSideAddr.setValue(6);

        spinArtIntAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinArtIntAddr.setValue(7);

        javax.swing.GroupLayout splPaneLayout = new javax.swing.GroupLayout(splPane);
        splPane.setLayout(splPaneLayout);
        splPaneLayout.setHorizontalGroup(
            splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSplIntDisplayBrd)
                    .addComponent(chkSplSideDisplayBrd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinArtSideAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinArtIntAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        splPaneLayout.setVerticalGroup(
            splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splPaneLayout.createSequentialGroup()
                .addGroup(splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSplSideDisplayBrd)
                    .addComponent(spinArtSideAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(splPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkSplIntDisplayBrd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinArtIntAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        chkPid.setFont(chkPid.getFont().deriveFont(chkPid.getFont().getStyle() | java.awt.Font.BOLD, chkPid.getFont().getSize()+5));
        chkPid.setText("PIDS");
        chkPid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPidActionPerformed(evt);
            }
        });

        chkDriverDb.setFont(chkDriverDb.getFont().deriveFont(chkDriverDb.getFont().getStyle() | java.awt.Font.BOLD, chkDriverDb.getFont().getSize()+5));
        chkDriverDb.setText("Driver Name Display on Internal Display");
        chkDriverDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDriverDbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkRearDisplayBrd)
                        .addComponent(chkFrontDisplayBrd))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkSideDisplayBrd)
                        .addComponent(chkIntDisplayBrd)))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisBrdMake, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBaudRate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNoRetries, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRetryWait, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDisBrdMake, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNoRetries, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRetryWaitTime, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGap, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(chkPid)
                        .addGap(18, 18, 18)
                        .addComponent(chkDriverDb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(splPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(lblConfigName, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(jCheckBox4)
                    .addGap(132, 132, 132)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(257, Short.MAX_VALUE)
                    .addComponent(jCheckBox5)
                    .addGap(122, 122, 122)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBaudRate, lblDisBrdMake, lblNoRetries, lblRetryWait});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbDisBrdMake, cmbNoRetries, cmbRetryWaitTime, txtBaudRate, txtGap});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblConfigName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFrontDisplayBrd)
                    .addComponent(chkSideDisplayBrd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRearDisplayBrd)
                    .addComponent(chkIntDisplayBrd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPid)
                    .addComponent(chkDriverDb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDisBrdMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisBrdMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaudRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNoRetries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoRetries, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRetryWaitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetryWait))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBaudRate, lblDisBrdMake, lblRetryWait});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbDisBrdMake, cmbNoRetries, cmbRetryWaitTime, txtBaudRate, txtGap});

        lblGap.getAccessibleContext().setAccessibleName("lblGap");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int baud_rate;

        byte brd_type;
        prev_control_name = "";
        try {

            if (cmbDisBrdMake.getSelectedItem().toString().equals("Sumith")) {
                brd_type = SUMITH_DISBRD;
                try {
                    baud_rate = Integer.parseInt(this.txtBaudRate.getText().trim());
                } catch (Exception ex) {
                    lblMsg.setText("Invalid Baudrate  " + ex.getMessage());
                    return;
                }
            } else {
                brd_type = KEMITO_DISBRD;
                baud_rate = KEMITO_BAUDRATE;
            }

            setDisBrdName(brd_type);
            setDisBrdBaudRate(baud_rate);

            if (radnormal.isSelected()) {
                setFrontEnable(chkFrontDisplayBrd.isSelected());
                setSideEnable(chkSideDisplayBrd.isSelected());
                setRearEnable(chkRearDisplayBrd.isSelected());
                setIntEnable(chkIntDisplayBrd.isSelected());
                clsSharedVariables.setArticulatedBus(false);
                clsSharedVariables.setArtSideEnable(false);
                clsSharedVariables.setArtIntEnable(false);
            } else {
                setFrontEnable(chkFrontDisplayBrd.isSelected());
                setSideEnable(chkSideDisplayBrd.isSelected());
                setRearEnable(chkRearDisplayBrd.isSelected());
                setIntEnable(chkIntDisplayBrd.isSelected());
                clsSharedVariables.setArticulatedBus(true);
                clsSharedVariables.setArtSideEnable(chkSplSideDisplayBrd.isSelected());
                clsSharedVariables.setArtIntEnable(chkSplIntDisplayBrd.isSelected());
                clsDefines.SD_ART_ADDR = Byte.parseByte(this.spinArtSideAddr.getValue().toString());
                clsDefines.ID_ART_ADDR = Byte.parseByte(this.spinArtIntAddr.getValue().toString());
            }

            if (chkFrontDisplayBrd.isSelected() == false) {
                lblFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fd_no_status.png"))); // NOI18N
            }
            if (chkSideDisplayBrd.isSelected() == false) {
                lblSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sd_no_status.png"))); // NOI18N
            }
            if (chkRearDisplayBrd.isSelected() == false) {
                lblRD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rd_no_status.png"))); // NOI18N
            }
            if (chkIntDisplayBrd.isSelected() == false) {
                lblID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/id_no_status.png"))); // NOI18N
            }

            if (clsSharedVariables.getArticulatedBus() == true) {
                if (clsSharedVariables.getArtSideEnable()) {
                    lblSDArt.setVisible(true);
                } else {
                    lblSDArt.setVisible(false);
                }
                if (clsSharedVariables.getArtIntEnable()) {
                    lblIDArt.setVisible(true);
                } else {
                    lblIDArt.setVisible(false);
                }
            } else {
                lblSDArt.setVisible(false);
                lblIDArt.setVisible(false);
            }
            if (chkPid.isSelected()) {
                clsSharedVariables.setPidsDbEnable(true);
            } else {
                clsSharedVariables.setPidsDbEnable(false);
            }

            if (chkDriverDb.isSelected()) {
                clsSharedVariables.setDisplayDriverDb(true);
            } else {
                clsSharedVariables.setDisplayDriverDb(false);
            }

            setDisBrdRetries(Integer.parseInt(cmbNoRetries.getSelectedItem().toString()));
            setDisbRdRetryWaitTime(Integer.parseInt(cmbRetryWaitTime.getText().trim()));
            setDisbRdGap(Integer.parseInt(txtGap.getText().trim()));

            clsReadFiles objReadFiles = new clsReadFiles();

            if (objReadFiles.write_cfg_data_file()) {
                lblMsg.setText("Configuration Saved");

            } else {
                lblMsg.setText("Configuration Not Saved");

            }

            if (clsSharedVariables.getFrontEnable()) {
                lblFD.setVisible(true);
            } else {
                lblFD.setVisible(false);
            }
            if (clsSharedVariables.getSideEnable()) {
                lblSD.setVisible(true);
            } else {
                lblSD.setVisible(false);
            }
            if (clsSharedVariables.getRearEnable()) {
                lblRD.setVisible(true);
            } else {
                lblRD.setVisible(false);
            }
            if (clsSharedVariables.getIntEnable()) {
                lblID.setVisible(true);
            } else {
                lblID.setVisible(false);
            }

            objReadFiles = null;
        } catch (Exception ex) {
            lblMsg.setText(ex.getMessage() + " Not Saved");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbDisBrdMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisBrdMakeActionPerformed
        // TODO add your handling code here:
        if (cmbDisBrdMake.getSelectedItem().equals("Sumith")) {
            txtBaudRate.setText(String.valueOf(clsSharedVariables.getDisBrdBaudRate()));
        } else {
            txtBaudRate.setText(String.valueOf(KEMITO_BAUDRATE));
        }
    }//GEN-LAST:event_cmbDisBrdMakeActionPerformed

    private void lblConfigNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblConfigNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConfigNameActionPerformed

    private void cmbRetryWaitTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRetryWaitTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRetryWaitTimeActionPerformed

    private void cmbRetryWaitTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRetryWaitTimeFocusLost
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_cmbRetryWaitTimeFocusLost

    private void cmbRetryWaitTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRetryWaitTimeFocusGained
        // TODO add your handling code here:
        if (!prev_control_name.equals("Retry Wait Time")) {
            clsKeyBoardView obj = new clsKeyBoardView();
            String str = obj.getKeyBoardValue("Retry Wait Time", cmbRetryWaitTime.getText());
            if (str != null) {
                cmbRetryWaitTime.setText(str);
            }
            prev_control_name = "Retry Wait Time";
            obj = null;
            str = null;
            cmbRetryWaitTime.transferFocusUpCycle();
        } else {
            prev_control_name = "";
        }
    }//GEN-LAST:event_cmbRetryWaitTimeFocusGained

    private void cmbNoRetriesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbNoRetriesFocusGained
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_cmbNoRetriesFocusGained

    private void chkFrontDisplayBrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrontDisplayBrdActionPerformed
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_chkFrontDisplayBrdActionPerformed

    private void chkFrontDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkFrontDisplayBrdFocusGained
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_chkFrontDisplayBrdFocusGained

    private void chkSideDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkSideDisplayBrdFocusGained
        prev_control_name = "";        // TODO add your handling code here:
    }//GEN-LAST:event_chkSideDisplayBrdFocusGained

    private void chkRearDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkRearDisplayBrdFocusGained
        prev_control_name = "";        // TODO add your handling code here:
    }//GEN-LAST:event_chkRearDisplayBrdFocusGained

    private void chkIntDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkIntDisplayBrdFocusGained
        prev_control_name = "";        // TODO add your handling code here:
    }//GEN-LAST:event_chkIntDisplayBrdFocusGained

    private void cmbDisBrdMakeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbDisBrdMakeFocusGained
        prev_control_name = "";        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDisBrdMakeFocusGained

    private void txtGapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGapFocusGained
        // TODO add your handling code here:
        if (!prev_control_name.equals("Gap")) {
            clsKeyBoardView obj = new clsKeyBoardView();
            String str = obj.getKeyBoardValue("Gap", txtGap.getText());
            if (str != null) {
                txtGap.setText(str);
            }
            prev_control_name = "Gap";
            obj = null;
            str = null;
            txtGap.transferFocusUpCycle();
        } else {
            prev_control_name = "";
        }
    }//GEN-LAST:event_txtGapFocusGained

    private void txtGapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGapFocusLost
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_txtGapFocusLost

    private void txtGapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGapActionPerformed

    private void radspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radspecialActionPerformed
        // TODO add your handling code here:
        if (radspecial.isSelected()) {

            splPane.setVisible(true);

        } else {

            splPane.setVisible(false);

        }
    }//GEN-LAST:event_radspecialActionPerformed

    private void radnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radnormalActionPerformed
        // TODO add your handling code here:
        if (radnormal.isSelected()) {

            splPane.setVisible(false);

        } else {

            splPane.setVisible(true);

        }
    }//GEN-LAST:event_radnormalActionPerformed

    private void chkSplSideDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkSplSideDisplayBrdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSplSideDisplayBrdFocusGained

    private void chkSplIntDisplayBrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chkSplIntDisplayBrdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSplIntDisplayBrdFocusGained

    private void chkRearDisplayBrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRearDisplayBrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRearDisplayBrdActionPerformed

    private void chkIntDisplayBrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntDisplayBrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIntDisplayBrdActionPerformed

    private void txtBaudRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBaudRateFocusGained
        // TODO add your handling code here
        if (!prev_control_name.equals("Baud")) {
            clsKeyBoardView obj = new clsKeyBoardView();
            String str = obj.getKeyBoardValue("Baud", txtBaudRate.getText());
            if (str != null) {
                txtBaudRate.setText(str);
            }
            prev_control_name = "Baud";
            obj = null;
            str = null;
            txtBaudRate.transferFocusUpCycle();
        } else {
            prev_control_name = "";
        }
    }//GEN-LAST:event_txtBaudRateFocusGained

    private void txtBaudRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBaudRateFocusLost
        // TODO add your handling code here:
        prev_control_name = "";
    }//GEN-LAST:event_txtBaudRateFocusLost

    private void chkPidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPidActionPerformed

    private void chkDriverDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDriverDbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDriverDbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkDriverDb;
    private javax.swing.JCheckBox chkFrontDisplayBrd;
    private javax.swing.JCheckBox chkIntDisplayBrd;
    private javax.swing.JCheckBox chkPid;
    private javax.swing.JCheckBox chkRearDisplayBrd;
    private javax.swing.JCheckBox chkSideDisplayBrd;
    private javax.swing.JCheckBox chkSplIntDisplayBrd;
    private javax.swing.JCheckBox chkSplSideDisplayBrd;
    private javax.swing.JComboBox cmbDisBrdMake;
    private javax.swing.JComboBox cmbNoRetries;
    private javax.swing.JTextField cmbRetryWaitTime;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBaudRate;
    private javax.swing.JTextField lblConfigName;
    private javax.swing.JLabel lblDisBrdMake;
    private javax.swing.JLabel lblGap;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNoRetries;
    private javax.swing.JLabel lblRetryWait;
    private javax.swing.JRadioButton radnormal;
    private javax.swing.JRadioButton radspecial;
    private javax.swing.JSpinner spinArtIntAddr;
    private javax.swing.JSpinner spinArtSideAddr;
    private javax.swing.JPanel splPane;
    private javax.swing.JTextField txtBaudRate;
    private javax.swing.JTextField txtGap;
    // End of variables declaration//GEN-END:variables
}
